<a href="https://colab.research.google.com/github/shafat0/Road-for-Data-Scientist/blob/main/scikit_learn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1. Getting our data ready  to be used with machine learning:-

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
heart_disease = pd.read_csv('/content/drive/MyDrive/heart-disease.csv')

In [6]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0


In [7]:
x = heart_disease.drop('target', axis = 1)

In [8]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3


In [9]:
y = heart_disease['target']

In [10]:
y

,target
0,1
1,1
2,1
3,1
4,1
...,...
298,0
299,0
300,0
301,0


In [11]:
# Split the data into training & test sets:-
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [12]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [13]:
x.shape[0] * 0.8

242.4

In [14]:
len(heart_disease)

303

## 1.1:-  Make sure it's all numerical:-

In [15]:
## we need another data set because heart_disease is already in numerical:-
car_sales = pd.read_csv('/content/drive/MyDrive/car-sales-extended.csv')

In [16]:
car_sales

,Make,Colour,Odometer (KM),Doors,Price
0,Honda,White,35431,4,15323
1,BMW,Blue,192714,5,19943
2,Honda,White,84714,4,28343
3,Toyota,White,154365,4,13434
4,Nissan,Blue,181577,3,14043
...,...,...,...,...,...
995,Toyota,Black,35820,4,32042
996,Nissan,White,155144,3,5716
997,Nissan,Blue,66604,4,31570
998,Honda,White,215883,4,4001


In [17]:
car_sales.head()

,Make,Colour,Odometer (KM),Doors,Price
0,Honda,White,35431,4,15323
1,BMW,Blue,192714,5,19943
2,Honda,White,84714,4,28343
3,Toyota,White,154365,4,13434
4,Nissan,Blue,181577,3,14043


In [18]:
len(car_sales)

1000

In [19]:
car_sales.dtypes

,0
Make,object
Colour,object
Odometer (KM),int64
Doors,int64
Price,int64


In [20]:
## Split the data into features and lebels:-
x = car_sales.drop('Price', axis =1)
y = car_sales['Price']

In [21]:
## Split into training and test:-
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = (0.2))

# Convert into numbers:-

In [22]:
car_sales["Doors"].value_counts()

,count
Doors,
4,856
5,79
3,65


In [23]:
## Turn the categories into numbers:-
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder = "passthrough")
transformed_x = transformer.fit_transform(x)
print(transformed_x)

[[0.00000e+00 1.00000e+00 0.00000e+00 ... 1.00000e+00 0.00000e+00
  3.54310e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 ... 0.00000e+00 1.00000e+00
  1.92714e+05]
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 1.00000e+00 0.00000e+00
  8.47140e+04]
 ...
 [0.00000e+00 0.00000e+00 1.00000e+00 ... 1.00000e+00 0.00000e+00
  6.66040e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 1.00000e+00 0.00000e+00
  2.15883e+05]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 1.00000e+00 0.00000e+00
  2.48360e+05]]


In [24]:
x.head()

,Make,Colour,Odometer (KM),Doors
0,Honda,White,35431,4
1,BMW,Blue,192714,5
2,Honda,White,84714,4
3,Toyota,White,154365,4
4,Nissan,Blue,181577,3


In [25]:
pd.DataFrame(transformed_x)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,35431.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,192714.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,84714.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,154365.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,181577.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,35820.0
996,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,155144.0
997,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,66604.0
998,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,215883.0


In [26]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True


In [27]:
# Let's refit the model
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)
x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size = (0.2))

model = RandomForestRegressor()
model.fit(x_train,y_train)

RandomForestRegressor()

In [28]:
## Built machine learning model:-
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.3281222657899089

In [29]:
model.score(x_test,y_test)

0.3281222657899089

## 1.2 What if there were missing values:-
    * 1. Fill them with some value (imputation).
    * 2. Remove the samples with missing data altogether.

In [30]:
# Import car sales missing data.
car_sales_missing = pd.read_csv('/content/drive/MyDrive/car-sales-extended-missing-data.csv')


In [31]:
car_sales_missing

,Make,Colour,Odometer (KM),Doors,Price
0,Honda,White,35431.0,4.0,15323.0
1,BMW,Blue,192714.0,5.0,19943.0
2,Honda,White,84714.0,4.0,28343.0
3,Toyota,White,154365.0,4.0,13434.0
4,Nissan,Blue,181577.0,3.0,14043.0
...,...,...,...,...,...
995,Toyota,Black,35820.0,4.0,32042.0
996,NaN,White,155144.0,3.0,5716.0
997,Nissan,Blue,66604.0,4.0,31570.0
998,Honda,White,215883.0,4.0,4001.0


In [32]:
car_sales_missing.isna().sum()

,0
Make,49
Colour,50
Odometer (KM),50
Doors,50
Price,50


In [33]:
## Create X & Y
x = car_sales_missing.drop('Price', axis = 1)
y = car_sales_missing['Price']

# Option 1:- FIll missing values with pandas:-

In [34]:
## Fill the "Make" column
car_sales_missing['Make'].fillna('missing', inplace = True)
## FIll tlhe " Colour" column
car_sales_missing['Colour'].fillna('missing', inplace = True)
## Fill the "Odometer (KM)" column
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(), inplace = True)
## Fill the 'Doors' column
car_sales_missing['Doors'].fillna(4, inplace = True)

/tmp/ipykernel_819/368420952.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car_sales_missing['Make'].fillna('missing', inplace = True)
/tmp/ipykernel_819/368420952.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)

In [35]:
car_sales_missing

,Make,Colour,Odometer (KM),Doors,Price
0,Honda,White,35431.0,4.0,15323.0
1,BMW,Blue,192714.0,5.0,19943.0
2,Honda,White,84714.0,4.0,28343.0
3,Toyota,White,154365.0,4.0,13434.0
4,Nissan,Blue,181577.0,3.0,14043.0
...,...,...,...,...,...
995,Toyota,Black,35820.0,4.0,32042.0
996,missing,White,155144.0,3.0,5716.0
997,Nissan,Blue,66604.0,4.0,31570.0
998,Honda,White,215883.0,4.0,4001.0


In [36]:
car_sales_missing.isna().sum()

,0
Make,0
Colour,0
Odometer (KM),0
Doors,0
Price,50


In [37]:
## Remove rows with missing Price value
car_sales_missing.dropna(inplace = True)

In [38]:
car_sales_missing.isna().sum()

,0
Make,0
Colour,0
Odometer (KM),0
Doors,0
Price,0


In [39]:
# Create X & Y
x = car_sales_missing.drop('Price', axis = 1)
y = car_sales_missing['Price']

In [40]:
## Turn the categories into numbers:-
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder = "passthrough")
transformed_car_sales_missing = transformer.fit_transform(car_sales_missing)
print(transformed_car_sales_missing)

[[0.00000e+00 1.00000e+00 0.00000e+00 ... 0.00000e+00 3.54310e+04
  1.53230e+04]
 [1.00000e+00 0.00000e+00 0.00000e+00 ... 1.00000e+00 1.92714e+05
  1.99430e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 0.00000e+00 8.47140e+04
  2.83430e+04]
 ...
 [0.00000e+00 0.00000e+00 1.00000e+00 ... 0.00000e+00 6.66040e+04
  3.15700e+04]
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 0.00000e+00 2.15883e+05
  4.00100e+03]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 0.00000e+00 2.48360e+05
  1.27320e+04]]


# Option 2:- Fill missing values with Scikit learn.

In [41]:
car_sales_missing = pd.read_csv('/content/drive/MyDrive/car-sales-extended-missing-data.csv')
car_sales_missing

,Make,Colour,Odometer (KM),Doors,Price
0,Honda,White,35431.0,4.0,15323.0
1,BMW,Blue,192714.0,5.0,19943.0
2,Honda,White,84714.0,4.0,28343.0
3,Toyota,White,154365.0,4.0,13434.0
4,Nissan,Blue,181577.0,3.0,14043.0
...,...,...,...,...,...
995,Toyota,Black,35820.0,4.0,32042.0
996,NaN,White,155144.0,3.0,5716.0
997,Nissan,Blue,66604.0,4.0,31570.0
998,Honda,White,215883.0,4.0,4001.0


In [42]:
# Let's check how many missing values do we have
car_sales_missing.isna().sum()

,0
Make,49
Colour,50
Odometer (KM),50
Doors,50
Price,50


In [43]:
# Now lets rid of the rows which don't have the 'Price' column value
car_sales_missing.dropna(subset = ['Price'], inplace = True)

In [44]:
car_sales_missing.isna().sum()

,0
Make,47
Colour,46
Odometer (KM),48
Doors,47
Price,0


In [45]:
# Split into x and y
x = car_sales_missing.drop('Price', axis = 1)
y = car_sales_missing['Price']

In [46]:
## Fill the missing values with the scikit learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
#1> Fill categorical values with "missing" and numerical values with mean
cat_imputer = SimpleImputer(strategy = 'constant', fill_value = 'missing')
door_imputer = SimpleImputer(strategy = 'constant', fill_value = 4)
num_imputer = SimpleImputer(strategy = 'mean')
#2> Define column
cat_feature = ['Make', 'Colour']
door_feature = ['Doors']
num_feature = ['Odometer (KM)']
#3> Create an imputer (Something that fills missing values)
imputer = ColumnTransformer([
    ('cat_imputer', cat_imputer,cat_feature),
    ('door_imputer', door_imputer,door_feature),
    ('num_imputer', num_imputer,num_feature)
])
#4> Transform the data
filled_x = imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [47]:
## Let's check now:-
car_sales_filled = pd.DataFrame(filled_x, columns = ['Make', 'Colour', 'Doors', 'Odometer (KM)'])
car_sales_filled

,Make,Colour,Doors,Odometer (KM)
0,Honda,White,4.0,35431.0
1,BMW,Blue,5.0,192714.0
2,Honda,White,4.0,84714.0
3,Toyota,White,4.0,154365.0
4,Nissan,Blue,3.0,181577.0
...,...,...,...,...
945,Toyota,Black,4.0,35820.0
946,missing,White,3.0,155144.0
947,Nissan,Blue,4.0,66604.0
948,Honda,White,4.0,215883.0


In [48]:
car_sales_filled.isna().sum()

,0
Make,0
Colour,0
Doors,0
Odometer (KM),0


In [49]:
## Let's convert the non-numerical data into numerical:-
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                remainder = 'passthrough')
transformed_x = transformer.fit_transform(car_sales_filled)
transformed_x

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3800 stored elements and shape (950, 15)>

In [50]:
pd.DataFrame(transformed_x)

,0
0,<Compressed Sparse Row sparse matrix of dtype ...
1,<Compressed Sparse Row sparse matrix of dtype ...
2,<Compressed Sparse Row sparse matrix of dtype ...
3,<Compressed Sparse Row sparse matrix of dtype ...
4,<Compressed Sparse Row sparse matrix of dtype ...
...,...
945,<Compressed Sparse Row sparse matrix of dtype ...
946,<Compressed Sparse Row sparse matrix of dtype ...
947,<Compressed Sparse Row sparse matrix of dtype ...
948,<Compressed Sparse Row sparse matrix of dtype ...


In [51]:
## Now we have got our data as numbers and filled the missing values
## Now let's fit the model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(transformed_x,y,test_size = (0.2))
model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.21990196728583944

##2:- Choosing the right estimator/algorithm for your problem:-
  # some things to note:-
    * Sk-learn refers to machine learning models, algorithms as estimators.
    * Classification problem - prediciting a category (heart disease or not).
      * Sometimes we'll see 'clf' (short for classifier) used as a classification estimatoe.
    * Regression problem - predicting a number (selling price of a car).

#If we're working on a machine learning problem and looking to use sklearn and not true what model you should use, refer to the sklearn machine learning map:- https://scikit-learn.org/1.3/tutorial/machine_learning_map/

In [52]:
### 2.1:- Picking a machine learning model for a regression problem:-
## Let's use the california housing dataset.
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [53]:
housing_df = pd.DataFrame(housing['data'],columns = housing["feature_names"])
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32


In [54]:
housing_df["MedHouseVal"] = housing["target"]
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


In [55]:
housing_df = housing_df.drop("MedHouseVal",axis = 1)

In [56]:
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32


In [57]:
housing_df['target'] = housing['target']

In [58]:
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


In [59]:
## import algorithm/estimator
from sklearn.linear_model import Ridge


## setup random seed
np.random.seed(42)
# create the data
x=housing_df.drop('target',axis=1)
y=housing_df['target'] ## Median house price in $100,000s

## Split into train and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate and fit the model ( on the training set)
model = Ridge()
model.fit(x_train,y_train)

# Check the score of the model ( on the test set)
model.score(x_test,y_test)

0.5758549611440126

In [60]:
from sklearn import svm

## setup random seed
np.random.seed(42)
# create the data
x=housing_df.drop('target',axis=1)
y=housing_df['target'] ## Median house price in $100,000s

## Split into train and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate and fit the model ( on the training set)
model = svm.SVR()
model.fit(x_train,y_train)

# Check the score of the model ( on the test set)
model.score(x_test,y_test)

-0.01648536010717372

In [61]:
from sklearn import linear_model
## setup random seed
np.random.seed(42)
# create the data
x=housing_df.drop('target',axis=1)
y=housing_df['target'] ## Median house price in $100,000s

## Split into train and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiate and fit the model ( on the training set)
model = linear_model.LinearRegression()
model.fit(x_train,y_train)

# Check the score of the model ( on the test set)
model.score(x_test,y_test)

0.5757877060324508

What if "Ridge" didn't work or the score didn't fit our needs?

Well, we could always try a different model.

How about we try an ensemble model (An ensemble is combination of smaller models to try and make better predictions than just a single model)?

sklearn ensemble model can be found here:-https://scikit-learn.org/1.3/modules/ensemble.html

In [62]:
#Import the random forest regressor model class from the ensemble module
from sklearn.ensemble import RandomForestRegressor
## setup random seed
np.random.seed(42)
# create the data
x=housing_df.drop('target',axis=1)
y=housing_df['target'] ## Median house price in $100,000s

## Split into train and test sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Create random forest model
model = RandomForestRegressor()
model.fit(x_train,y_train)

# Check the score of the model ( on the test set)
model.score(x_test,y_test)

0.8066196804802649

# 2.2 Choosing an estimator for a CLASSIFICATION PROBLEM:-
Let's go to the map:- https://scikit-learn.org/1.3/tutorial/machine_learning_map/

In [63]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0


In [64]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1


In [65]:
len(heart_disease)

303

** Consulting  the map and it says to try LinearSVC

In [66]:
# Import the LinearSVC estimator class
from sklearn.svm import LinearSVC

# Setup Random seed
np.random.seed(42)
# Make the data
x  =  heart_disease.drop("target", axis = 1)
y = heart_disease["target"]
# Split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
# Instance the model
clf = LinearSVC()
clf.fit(x_train,y_train)
# Check the score of the model
clf.score(x_test,y_test)

0.8688524590163934

# What if this algorithm is not working:-


In [67]:
# Import the random forest classifier class
from sklearn.ensemble import RandomForestClassifier

# Setup Random seed
np.random.seed(42)
# Make the data
x  =  heart_disease.drop("target", axis = 1)
y = heart_disease["target"]
# Split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
# Instance the RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(x_train,y_train)
# Check the score of the model
clf.score(x_test,y_test)

0.8524590163934426

## NOTE:-
* If we have structured data(tables or dataframes) use ensemble methods such as RandomForest.
* If we have unstructured data(images,audio,text etc) use deep learning or transfer learning.

# 3> Fit the model/algoritm and use it to make predictions on our data.



## 3.1 Fitting the model to the data.
    ** Different names for:-
    * x = features,feature variables,data.
    * y = labels, targets, target_variables.

In [68]:
# Import the random forest classifier class
from sklearn.ensemble import RandomForestClassifier

# Setup Random seed
np.random.seed(42)
# Make the data
x  =  heart_disease.drop("target", axis = 1)
y = heart_disease["target"]
# Split the data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
# Instance the RandomForestClassifier
clf = RandomForestClassifier()
# Fit the model to the data (training the machine learning model)
clf.fit(x_train,y_train)
# Check the score of the model (use the paterns the model has learned)
clf.score(x_test,y_test)

0.8524590163934426

In [69]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2


In [70]:
y.head()

,target
0,1
1,1
2,1
3,1
4,1


## NOTE:- What does fit actually do:- When we pass x and y to fit it will cause the model to go through all the examples in x the training data in our case and see what the corresponding y label is and try to figure out the paterns that leads so that different combination of numbers here what leads to having a 1 or 0 as a label.

## 3.2> Making Predictions with macine learning model.
      * 2 ways:-
          *1> predict()
          *2> predict_proba()


In [71]:
# Use a trained model to make predictions
clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [72]:
np.array(y_test) # Truth labels

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [73]:
## Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(x_test)
np.mean(y_preds == y_test)

np.float64(0.8524590163934426)

In [74]:
clf.score(x_test,y_test)

0.8524590163934426

In [75]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

# Make predictions with predict_proba():-
    * predict_proba() returns probablities of a classificaiton label.

In [76]:
clf.predict_proba(x_test)

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82],
       [0.14, 0.86],
       [0.36, 0.64],
       [0.95, 0.05],
       [0.99, 0.01],
       [0.47, 0.53],
       [0.26, 0.74],
       [0.7 , 0.3 ],
       [0.11, 0.89],
       [0.95, 0.05],
       [0.03, 0.97],
       [0.02, 0.98],
       [0.01, 0.99],
       [0.84, 0.16],
       [0.95, 0.05],
       [0.98, 0.02],
       [0.51, 0.49],
       [0.89, 0.11],
       [0.38, 0.62],
       [0.29, 0.71],
       [0.26, 0.74],
       [0.34, 0.66],
       [0.2 , 0.8 ],
       [0.22, 0.78],
       [0.83, 0.17],
       [0.15, 0.85],
       [0.94, 0.06],
       [0.92, 0.08],
       [0.96, 0.04],
       [0.62, 0.38],
       [0.46, 0.54],
       [0.89, 0.11],
       [0.44, 0.56],
       [0.16, 0.84],
       [0.33, 0.67],
       [0.08, 0.92],
       [0.13, 0.87],
       [0.17, 0.83],
       [0.18, 0.82],
       [0.38, 0.62],
       [0.32, 0.68],
       [0.77, 0.23],
       [0.39, 0.61],
       [0.  ,

In [77]:
# Let's predict() on the same data:-
clf.predict(x_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [78]:
heart_disease['target'].value_counts()

,count
target,
1,165
0,138


## Making predictions with our Model Regression:-
      * 'predict()' can also be used for Regression Models.

In [79]:
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422


In [80]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
# Create the data
x = housing_df.drop('target', axis = 1)
y = housing_df['target']
# Split into training and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
# Create model instance
model = RandomForestRegressor()
# Fit the model to the data
model.fit(x_train,y_train)
# Make predictions
y_pred = model.predict(x_test)
y_pred

array([0.49384  , 0.75494  , 4.9285964, ..., 4.8363785, 0.71782  ,
       1.67901  ])

In [81]:
y_pred[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54029  , 2.33176  , 1.6549701,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [83]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [84]:
len(y_pred)

4128

In [86]:
len(y_test)

4128

In [87]:
## Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.3265721842781009

In [88]:
housing_df['target']

,target
0,4.526
1,3.585
2,3.521
3,3.413
4,3.422
...,...
20635,0.781
20636,0.771
20637,0.923
20638,0.847


## 4. Evaluating a machine learning model:-
      * Three ways to evaluate scikit-learn models/estimators:_
          * 1> Estimator's built-in "score()" method.
          * 2> The 'scoring' parameter.
          * 3> Problem-specific metric functions.

* We can read more about here:-https://scikit-learn.org/stable/modules/model_evaluation.html

# 4.1> Evaluating a model with the score () method.

In [89]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)
#create x and y
x = heart_disease.drop('target',axis = 1)
y = heart_disease['target']
# create train and test sets.
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
# create classifier model instance
clf = RandomForestClassifier()
# Fit the classifier
clf.fit(x_train,y_train)


RandomForestClassifier()

In [91]:
# use score() method
clf.score(x_train,y_train)
# The highest value for the score() method is 1.0 the lowest is 0.0

1.0

In [92]:
clf.score(x_test,y_test)

0.8524590163934426

** Let's use the score() method on regression problem

In [93]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)
# create x and y
x = housing_df.drop('target',axis = 1)
y = housing_df['target']
# create train and test sets.
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
# create classifier model instance
model = RandomForestRegressor()
# Fit the classifier
model.fit(x_train,y_train)

RandomForestRegressor()

In [94]:
model.score(x_train,y_train)

0.9736828565983116

In [95]:
model.score(x_test,y_test)

0.8066196804802649